### ISSUE TITLE
Help with part 4 - error after create Mail Provider

### ISSUE THREAD

**Issue by othin1** [railsfactory-sivamanikandan/redmine_mail_ticket_sync_pro#2]
hello, i followed the guide and did all the required, but i got stuck as soon as i created the email provider.

In fact if I complete 

Name
Client
Client secret
Tenant
Callback url

I get this error back from the logs:

```
I, [2024-12-09T15:48:47.365828 #1]  INFO -- : Started POST "/admin/mail_ticket_providers" for 172.69.68.57 at 2024-12-09 15:48:47 +0100
I, [2024-12-09T15:48:47.368144 #1]  INFO -- : Processing by Admin::MailTicketProvidersController#create as HTML
I, [2024-12-09T15:48:47.368277 #1]  INFO -- :   Parameters: {"authenticity_token"=>"g-8jAmNkRMKe0grVedw-61-NOAZR2gdLG23rRBZkoV17_pClzazYxOtykJUN64v70HJIoUyx7jTioxEUpDuAqQ", "mail_ticket_provider"=>{"name"=>"outlook", "client_id"=>"[FILTERED]", "client_secret"=>"[FILTERED]", "tenant_id"=>"[FILTERED]", "callback_url"=>"https://login.microsoftonline.com"}, "commit"=>"Create"}
I, [2024-12-09T15:48:47.375253 #1]  INFO -- :   Current user: myuser (id=7)
I, [2024-12-09T15:48:47.377453 #1]  INFO -- : Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.5ms (3 queries, 0 cached) | GC: 0.0ms)
F, [2024-12-09T15:48:47.379634 #1] FATAL -- :
ActiveRecord::Encryption::Errors::Configuration (Missing Active Record encryption credential: active_record_encryption.primary_key):

plugins/redmine_mail_ticket_sync_pro/app/controllers/admin/mail_ticket_providers_controller.rb:18:in `create'
lib/redmine/sudo_mode.rb:78:in `sudo_mode'
```

I think it is due to a missing step before step 4

my /usr/src/redmine/plugins/redmine_mail_ticket_sync_pro/config/application.yml is:

active_record_encryption:
  primary_key: <%= ENV["hide"] %>
  secondary_key: <%= ENV["hide"] %>
  key_derivation_salt: <%= ENV["hide"] %>

Thanks very much

**Comment by railsfactory-sivamanikandan** [comment]
@othin1 Please follow this link to set active_record_encryption. I will update the readme ASAP
https://guides.rubyonrails.org/active_record_encryption.html

**Comment by othin1** [comment]
thank you for your answer, very usefull, i've resolved.

**Comment by railsfactory-sivamanikandan** [comment]
@othin1 I have updated the readme file also. Please share your feedback once the setup is done
