### ISSUE TITLE
Token expired & failure to update email cron

### ISSUE THREAD

**Issue by othin1** [railsfactory-sivamanikandan/redmine_mail_ticket_sync_pro#3]
Hi, First of all I wanted to thank you for your “creation,” it is really saving me since we switched to microsoft 365

Unfortunately, I've been stuck on two points for a few days, the first one:

I realized that after about a day the token used to connect to the mail account expires:

```
I, [2024-12-18T08:02:26.564560 #1]  INFO -- : Started GET "/admin/mail_job_schedules/start_mail_sync/1" for ... at 2024-12-18 08:02:26 +0100
I, [2024-12-18T08:02:26.567132 #1]  INFO -- : Processing by Admin::MailJobSchedulesController#start_mail_sync as HTML
I, [2024-12-18T08:02:26.567233 #1]  INFO -- :   Parameters: {"id"=>"1"}
I, [2024-12-18T08:02:26.575188 #1]  INFO -- :   Current user: ... (id=7)
E, [2024-12-18T08:02:27.018287 #1] ERROR -- : Access token expired, refreshing...
E, [2024-12-18T08:02:27.021524 #1] ERROR -- : Token refresh failed: {}
I, [2024-12-18T08:02:27.022861 #1]  INFO -- : Completed 500 Internal Server Error in 455ms (ActiveRecord: 4.3ms (10 queries, 1 cached) | GC: 0.4ms)
F, [2024-12-18T08:02:27.025355 #1] FATAL -- :
ArgumentError ('3' is not a valid sync_status):

Causes:
OAuth2::Error ({})

plugins/redmine_mail_ticket_sync_pro/app/services/outlook_mail_service.rb:137:in `rescue in refresh_access_token'
plugins/redmine_mail_ticket_sync_pro/app/services/outlook_mail_service.rb:126:in `refresh_access_token'
plugins/redmine_mail_ticket_sync_pro/app/services/outlook_mail_service.rb:112:in `refresh_token_if_expired'
plugins/redmine_mail_ticket_sync_pro/app/services/outlook_mail_service.rb:14:in `initialize'
plugins/redmine_mail_ticket_sync_pro/app/controllers/admin/mail_job_schedules_controller.rb:84:in `new'
plugins/redmine_mail_ticket_sync_pro/app/controllers/admin/mail_job_schedules_controller.rb:84:in `start_mail_sync'
lib/redmine/sudo_mode.rb:78:in `sudo_mode'
```
If i re-atuthenticate the mail the manual sync-mail run correctly, is a my error?

The second question is for the cron, 

![image](https://github.com/user-attachments/assets/3a5b01c9-6736-42e9-bd23-f4f9284bc0de)

If you look at the image you will see that I have set the cron to check emails every minute, however, this does not happen.
Could I have made a mistake here too? do you think there is maybe a script that I can make myself and start from my server?
For example in the past I simply did:

```
cd /usr/src/redmine/
rake redmine:email:receive_imap \
        RAILS_ENV=production \
        host=imap.gmail.com port=993 ssl=true \
        username=myemail@gmail.com password="app-password" \
        project=assistenza tracker=support \
        unknown_user=accept no_permission_check=1

```

there are no failure or attempt logs.

I return the thanks towards you for your work done

**Comment by railsfactory-sivamanikandan** [comment]
@othin1 Did you pulled my latest changes?
If yes then new token will be automatically updated using the refresh token from cron or manual sync
Regarding the crontab
Check your system is blocking to update crontab or crontab is updated 
using the below command
`crontab -e`

**Comment by othin1** [comment]
hello, thank you in the meantime for your reply
I did subsequently pull but a parameter in routes.rb changed so now I am trying to solve that part (I need to figure out the callbackurl, before it was https://mysite/auth/callback
Now is different
For the crontab i've a redmine in docker, so the crontab is outside

**Comment by railsfactory-sivamanikandan** [comment]
Yes, now i have added support to gmail & outlook so you need to build callback url like below
https://mysite/auth/callback/gmail
https://mysite/auth/callback/outlook
you need to pass the provider in the url like above

**Comment by railsfactory-sivamanikandan** [comment]
May be that cause issue in running cron as it couldn't find the application path

**Comment by othin1** [comment]
YEah thanks
![image](https://github.com/user-attachments/assets/69417561-7d1e-4393-8853-e0b732a92865)
Now I understand how it works, basically failing to call the cron also expires the token...clear the problem now I have to find a way to call the cron from outside...
Maybe I can do as I used to do in the past :

docker exec -i deployment_redmine_1 /bin/bash /usr/src/redmine/path-of-cron

what do you think, could I do it?

**Comment by othin1** [comment]
meanwhile i', working on this call: "curl -s https://mysite/admin/mail_job_schedules/start_mail_sync/2"
maybe i can simulate the manual call

**Comment by railsfactory-sivamanikandan** [comment]
Yes it should work for running cronjob, okay

**Comment by othin1** [comment]
unfortunately calling that url from within the server doesn't help, without the token it's no use...I'll keep trying to make it docker compatible, I'm so close to it now

**Comment by othin1** [comment]
i've two way now:

1: use this command: `RAILS_ENV=production project=assistenza email=myemail bundle exec rake emails:fetch_and_create_issues` But I need to fix something...I'm starting it in /usr/src/redmine

second way, stupid not to think of it earlier, install cron in the docker with the classic “apt install cron”

**Comment by railsfactory-sivamanikandan** [comment]
I hope it is working as expected

**Comment by othin1** [comment]
I realized two things, the first is that probably if I in docker had installed and activated “cron” maybe everything would have gone as it should (in the official redmine docker it is inactive). I should do some testing but I can't right now, in case I will write you.

Second thing you can do cron externally with this command:

`* * * * * * docker exec deployment_redmine_1 /bin/bash -l -c 'cd /usr/src/redmine && RAILS_ENV=production bundle exec rake emails:fetch_and_create_issues project=assistance email=myemail@sirmioneservizi.it --silent >> /usr/src/redmine/app/log/assistance_services-it.log 2>&1'`

The only issue (there is never peace...) is that it does not send emails to every ticket generated.

I will investigate this aspect at my leisure.
thanks for the patience
